# Scikit-learn

In [330]:
# a Python library used for Machine Learning models and data preprocessing
# Prepare data
# Train ML models
# Test model performance

In [331]:
import pandas as pd

In [332]:
df = pd.read_csv("house_prices.csv")

In [333]:
df

    Size_sqft  Bedrooms  Age  Location   Price
0        1200         2   10     Urban  200000
1        1500         3    5     Urban  250000
2        1800         3    8  Suburban  270000
3        2000         4    2  Suburban  320000
4        1100         2   15     Rural  180000
5        1700         3    7     Urban  260000
6        1400         2   12     Rural  210000
7        2100         4    3  Suburban  330000
8        1600         3    6     Urban  255000
9        1900         3    4  Suburban  300000
10       1300         2   11     Rural  195000
11       1750         3    6     Urban  265000
12       1550         3    9  Suburban  240000
13       1650         3    5     Urban  250000
14       2200         4    2  Suburban  350000

In [334]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Size_sqft  15 non-null     int64
 1   Bedrooms   15 non-null     int64
 2   Age        15 non-null     int64
 3   Location   15 non-null     object
 4   Price      15 non-null     int64
dtypes: int64(4), object(1)
memory usage: 732.0+ bytes

In [335]:
df.head()

   Size_sqft  Bedrooms  Age  Location   Price
0       1200         2   10     Urban  200000
1       1500         3    5     Urban  250000
2       1800         3    8  Suburban  270000
3       2000         4    2  Suburban  320000
4       1100         2   15     Rural  180000

In [336]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Size_sqft  15 non-null     int64
 1   Bedrooms   15 non-null     int64
 2   Age        15 non-null     int64
 3   Location   15 non-null     object
 4   Price      15 non-null     int64
dtypes: int64(4), object(1)
memory usage: 732.0+ bytes

In [337]:
df.isnull().sum()

Size_sqft    0
Bedrooms     0
Age          0
Location     0
Price        0
dtype: int64

# Identify Features (X) and Target (y)

In [338]:
#| Type         | Meaning                             |
#| ------------ | ----------------------------------- |
#| Features (X) | Input variables used for prediction |
#| Target (y)   | Output variable we want to predict  |

In [339]:
X = df[["Size_sqft","Bedrooms","Age","Location"]]
X.head()

   Size_sqft  Bedrooms  Age  Location
0       1200         2   10     Urban
1       1500         3    5     Urban
2       1800         3    8  Suburban
3       2000         4    2  Suburban
4       1100         2   15     Rural

In [340]:
y = df["Price"]
y.head()

0    200000
1    250000
2    270000
3    320000
4    180000
Name: Price, dtype: int64

# Handle Categorical Data

In [341]:
# Machine learning models cannot understand text
# Here it is Location
# convert categories → numbers
# location col must be encoded

In [342]:
# One-Hot Encoding
# sklearn - scikit-learn => "Scientific Kit for Learning"

In [343]:
from sklearn.preprocessing import OneHotEncoder

In [344]:
# Create encoder object
# OneHotEncoder()	create encoder object
# encoder	variable storing that object
encoder = OneHotEncoder()

In [345]:
# encoded_location = encoder.fit_transform((df["Location"])) === error
 
# df["Location"] → Series (1D) ====== NO
# OneHotEncoder needs → DataFrame / 2D array ==== YES

In [346]:
# double brackets so pandas sends a DataFrame (2D)

# Fit encoder and transform Location column

#| fit()       | learn the categories           |
#| transform() | convert them to binary columns |

encoded_location = encoder.fit_transform(df[["Location"]])

In [347]:
#Categories found :
# Rural
# Suburban
# Urban
# O/P becomes
# [[0 0 1]
# [0 0 1]
# [0 1 0]]

# Sparse Matrix stores only non-zero values to save memory
# (0, 2)  1.0 [Row index = 0 | Column index = 2  | Value = 1] -- [0 0 1]

print(encoded_location)
print("---------------")
print(encoded_location.toarray())

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15 stored elements and shape (15, 3)>
  Coords	Values
  (0, 2)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 0)	1.0
  (5, 2)	1.0
  (6, 0)	1.0
  (7, 1)	1.0
  (8, 2)	1.0
  (9, 1)	1.0
  (10, 0)	1.0
  (11, 2)	1.0
  (12, 1)	1.0
  (13, 2)	1.0
  (14, 1)	1.0
---------------
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

In [348]:
# Convert encoded result to DataFrame with proper column names
# encoded_df = pd.DataFrame(encoded_location.toarray())

encoded_df = pd.DataFrame(
    encoded_location.toarray(),
    columns = encoder.get_feature_names_out(["Location"])
)

In [349]:
# pd.DataFrame() converts data into a table format (rows & columns)
# encoded data into a proper table

# encoded_location.toarray() === convert sparse matrix → normal array
# OneHotEncoder returned a Sparse Matrix
# sparse format -- (0,2) 1
# but DataFrames need normal array data
# we convert it to a NumPy array

# columns
# we don’t give it, pandas will create 0 1 2
# get_feature_names_out : generates column names automatically based on original column

In [350]:
# Remove Original Location Column
df = df.drop("Location", axis=1)

In [351]:
df

    Size_sqft  Bedrooms  Age   Price
0        1200         2   10  200000
1        1500         3    5  250000
2        1800         3    8  270000
3        2000         4    2  320000
4        1100         2   15  180000
5        1700         3    7  260000
6        1400         2   12  210000
7        2100         4    3  330000
8        1600         3    6  255000
9        1900         3    4  300000
10       1300         2   11  195000
11       1750         3    6  265000
12       1550         3    9  240000
13       1650         3    5  250000
14       2200         4    2  350000

In [352]:
# Combine Encoded Columns
df = pd.concat([df,encoded_df],axis=1)

In [353]:
df

,Size_sqft,Bedrooms,Age,Price,Location_Rural,Location_Suburban,Location_Urban
0,1200,2,10,200000,0.0,0.0,1.0
1,1500,3,5,250000,0.0,0.0,1.0
2,1800,3,8,270000,0.0,1.0,0.0
3,2000,4,2,320000,0.0,1.0,0.0
4,1100,2,15,180000,1.0,0.0,0.0
5,1700,3,7,260000,0.0,0.0,1.0
6,1400,2,12,210000,1.0,0.0,0.0
7,2100,4,3,330000,0.0,1.0,0.0
8,1600,3,6,255000,0.0,0.0,1.0
9,1900,3,4,300000,0.0,1.0,0.0
10,1300,2,11,195000,1.0,0.0,0.0
11,1750,3,6,265000,0.0,0.0,1.0
12,1550,3,9,240000,0.0,1.0,0.0
13,1650,3,5,250000,0.0,0.0,1.0
14,2200,4,2,350000,0.0,1.0,0.0

In [354]:
X = df[["Size_sqft","Bedrooms","Age","Location_Rural","Location_Suburban","Location_Urban"]]
X.head()

   Size_sqft  Bedrooms  Age  Location_Rural  Location_Suburban  Location_Urban
0       1200         2   10             0.0                0.0             1.0
1       1500         3    5             0.0                0.0             1.0
2       1800         3    8             0.0                1.0             0.0
3       2000         4    2             0.0                1.0             0.0
4       1100         2   15             1.0                0.0             0.0

In [355]:
y = df["Price"]
y.head()

0    200000
1    250000
2    270000
3    320000
4    180000
Name: Price, dtype: int64

# How OneHotEncoder works

In [356]:
# OneHotEncoder reads the data, it automatically sorts them alphabetically
# if col has [ Urban Rural Suburban ]
# then order becomes [ Rural Suburban Urban ]

# For each row
# Put 1 in the column that matches the category
# Put 0 in all other columns
#| Location | Rural | Suburban | Urban |
#| -------- | ----- | -------- | ----- |
#| Urban    | 0     | 0        | 1     |
#| Rural    | 1     | 0        | 0     |
#| Suburban | 0     | 1        | 0     |

# Rural     → [1 0 0]
# Suburban  → [0 1 0]
# Urban     → [0 0 1]

# Feature Scaling

In [357]:
# Our dataset has different range values
# Large values like 2000 dominate smaller values like 3 or 1

# Size_sqft	2000
# Bedrooms	3

# We use standardization
# Z = (X − mean) / standard deviation
# After scaling, values look like: -1.3, 0.4, 1.2 (similar scale)

In [358]:
from sklearn.preprocessing import StandardScaler

In [359]:
scaler = StandardScaler()

In [360]:
X.head()

   Size_sqft  Bedrooms  Age  Location_Rural  Location_Suburban  Location_Urban
0       1200         2   10             0.0                0.0             1.0
1       1500         3    5             0.0                0.0             1.0
2       1800         3    8             0.0                1.0             0.0
3       2000         4    2             0.0                1.0             0.0
4       1100         2   15             1.0                0.0             0.0

In [361]:
# fit()	learn mean & std from data
# transform()	scale the data
# fit_transform()	do both together
X_scaled = scaler.fit_transform(X)

In [364]:
print(X_scaled)

[[-1.44735192 -1.37281295  0.81348922 -0.5        -0.81649658  1.22474487]
 [-0.48245064  0.09805807 -0.54232614 -0.5        -0.81649658  1.22474487]
 [ 0.48245064  0.09805807  0.27116307 -0.5         1.22474487 -0.81649658]
 [ 1.12571816  1.56892908 -1.35581536 -0.5         1.22474487 -0.81649658]
 [-1.76898568 -1.37281295  2.16930458  2.         -0.81649658 -0.81649658]
 [ 0.16081688  0.09805807  0.         -0.5        -0.81649658  1.22474487]
 [-0.8040844  -1.37281295  1.35581536  2.         -0.81649658 -0.81649658]
 [ 1.44735192  1.56892908 -1.08465229 -0.5         1.22474487 -0.81649658]
 [-0.16081688  0.09805807 -0.27116307 -0.5        -0.81649658  1.22474487]
 [ 0.8040844   0.09805807 -0.81348922 -0.5         1.22474487 -0.81649658]
 [-1.12571816 -1.37281295  1.08465229  2.         -0.81649658 -0.81649658]
 [ 0.32163376  0.09805807 -0.27116307 -0.5        -0.81649658  1.22474487]
 [-0.32163376  0.09805807  0.54232614 -0.5         1.22474487 -0.81649658]
 [ 0.          0.09805807 -0.54232614 -0.5        -0.81649658  1.22474487]
 [ 1.76898568  1.56892908 -1.35581536 -0.5         1.22474487 -0.81649658]]

In [365]:
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)
print(X_scaled_df)

    Size_sqft  Bedrooms       Age  Location_Rural  Location_Suburban  \
0   -1.447352 -1.372813  0.813489            -0.5          -0.816497
1   -0.482451  0.098058 -0.542326            -0.5          -0.816497
2    0.482451  0.098058  0.271163            -0.5           1.224745
3    1.125718  1.568929 -1.355815            -0.5           1.224745
4   -1.768986 -1.372813  2.169305             2.0          -0.816497
5    0.160817  0.098058  0.000000            -0.5          -0.816497
6   -0.804084 -1.372813  1.355815             2.0          -0.816497
7    1.447352  1.568929 -1.084652            -0.5           1.224745
8   -0.160817  0.098058 -0.271163            -0.5          -0.816497
9    0.804084  0.098058 -0.813489            -0.5           1.224745
10  -1.125718 -1.372813  1.084652             2.0          -0.816497
11   0.321634  0.098058 -0.271163            -0.5          -0.816497
12  -0.321634  0.098058  0.542326            -0.5           1.224745
13   0.000000  0.098058 -0.542326            -0.5          -0.816497
14   1.768986  1.568929 -1.355815            -0.5           1.224745

    Location_Urban
0         1.224745
1         1.224745
2        -0.816497
3        -0.816497
4        -0.816497
5         1.224745
6        -0.816497
7        -0.816497
8         1.224745
9        -0.816497
10       -0.816497
11        1.224745
12       -0.816497
13        1.224745
14       -0.816497

In [366]:
# We usually do NOT scale one-hot encoded columns
# for learning purposes it's fine if you scaled them

# Train–Test Split

In [368]:
# Training Data	Used to train the model - 80%
# Testing Data	Used to test the model - 20%

In [369]:
from sklearn.model_selection import train_test_split

In [376]:
# Random_state=42  == fixed random split
# shuffled randomly each time
# RUN 1 :: Train: rows 1,3,4,6,7... | Test : rows 2,5 (random 80% test and random 20% test)
# RUN 2 :: Train: rows 2,4,5,7... | Test : rows 1,6 

# random_state = 42 means each run
# Train: same rows
# Test : same rows

In [377]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size = 0.2, random_state = 42
)

In [382]:
# Dataset = 15 rows (20% of 15 = 3 for Testing | 12 for Training)

print(X_train.shape) # 12 rows 6 cols
print(X_test.shape) # 3 rows 6 cols
print(y_train.shape) # 12 target values
print(y_test.shape) # 3 target values

(12, 6)
(3, 6)
(12,)
(3,)

# Train the Machine Learning Model

In [383]:
# Only Regression models : predict continuous values

# Classification : used when the target is categories.
# Ex: Spam Detection ->	Spam / Not Spam

# Linear Regression

In [392]:
#x1 = Size_sqft
#x2 = Bedrooms
#x3 = Age
#x4 = Location_Rural
#x5 = Location_Suburban
#x6 = Location_Urban

#Price =
#b0 +
#b1*(Size_sqft) +
#b2*(Bedrooms) +
#b3*(Age) +
#b4*(Location_Rural) +
#b5*(Location_Suburban) +
#b6*(Location_Urban)

#Size_sqft = 1700
#Bedrooms = 3
#Age = 7
#Location_Urban = 1
#Location_Suburban = 0
#Location_Rural = 0

#Predicted Price =
#b0 +
#b1*1700 +
#b2*3 +
#b3*7 +
#b4*0 +
#b5*0 +
#b6*1

# o/p values
#277539.63
#267622.48
#176614.27

In [384]:
from sklearn.linear_model import LinearRegression

In [385]:
model = LinearRegression()

In [386]:
# Train Model
model.fit(X_train, y_train)

LinearRegression()

In [390]:
model.coef_
model.intercept_
print(model.coef_)
print(model.intercept_)

[31349.70129462 24259.12472906   120.78892331  4244.19244743
 -2992.21770792  -473.1509142 ]
255451.75969760356

In [387]:
y_pred = model.predict(X_test)

In [394]:
print(y_test.values)
print(y_pred)

[300000 265000 200000]
[277539.634482   267622.48155896 176614.2794231 ]

In [396]:
y_pred = y_pred.round().astype(int)
print(y_pred)

[277540 267622 176614]

In [397]:
# Evaluate Model
from sklearn.metrics import mean_squared_error, r2_score

In [398]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_test)

In [ ]:
# Measures average prediction error
# Lower = better.

In [418]:
print("Mean squared error: ",mse)
print("R2 Score", r2)

Mean squared error:  352743826.6666667
R2 Score 1.0

In [401]:
#| R²   | Meaning       |
#| ---- | ------------- |
#| 1.0  | Perfect model |
#| 0.8+ | Very good     |
#| 0.5  | Moderate      |
#| 0    | Poor          |

# Decision Tree

In [403]:
# Decision Tree splits the data into rules

In [404]:
from sklearn.tree import DecisionTreeRegressor

In [409]:
# Create Model
dt_model = DecisionTreeRegressor(random_state= 42)

In [410]:
# Train model
dt_model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [415]:
# Make Predictions
y_pred_dt = dt_model.predict(X_test)

In [416]:
print(y_test.values)
print(y_pred_dt)

[300000 265000 200000]
[320000. 260000. 255000.]

In [419]:
# Evaluate model
mse_dt = mean_squared_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test,y_pred_dt)

In [420]:
print("Mean squared error: ",mse_dt)
print("R2 Score", r2_dt)

Mean squared error:  1150000000.0
R2 Score 0.33009708737864074

In [421]:
# Decision Trees usually need more data to learn good splitting rules
# so Predictions become unstable

# Linear regression r2=1 | better model
# Bigger house → Higher price

# Random Forest

In [422]:
# Random Forest Regressor
# it fixes the biggest problem of Decision Trees: Overfitting
# Random Forest = many decision trees combined.

In [423]:
from sklearn.ensemble import RandomForestRegressor

In [427]:
# Create Model
# n_estimators=100 :: number of trees in forest
rf_model = RandomForestRegressor(
    n_estimators = 100,
    random_state=42
)

In [429]:
# Train the Model
rf_model.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [430]:
# Make Predictions
y_pred_rf = rf_model.predict(X_test)

In [432]:
print(y_test.values)
print(y_pred_rf)

[300000 265000 200000]
[278000. 258750. 213200.]

In [433]:
mse_rf = mean_squared_error(y_test,y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

In [434]:
print("Mean squared error: ",mse_rf)
print("R2 Score", r2_rf)

Mean squared error:  232434166.66666666
R2 Score 0.8646014563106796

In [435]:
#Random Forest works using a method called Bagging (Bootstrap Aggregation):
#Multiple Trees
#     ↓
#Different subsets of data
#     ↓
#Average predictions
#     ↓
#Better accuracy

# Support Vector Regressor

In [436]:
from sklearn.svm import SVR

In [438]:
# Create Model
svr_model = SVR(kernel='rbf')
# kernel='rbf' :: Allows non-linear relationships

In [439]:
# Train Model
svr_model.fit(X_train,y_train)

SVR()

In [440]:
# Make predictions
y_pred_svr = svr_model.predict(X_test)

In [444]:
#Evaluate Model
mse_svr = mean_squared_error(y_test.values, y_pred_svr)
r2_svr = r2_score(y_test.values, y_pred_svr)

In [445]:
print("SVR MSE:", mse_svr)
print("SVR R2:", r2_svr)

SVR MSE: 1722832771.1899757
SVR R2: -0.003591905547558616